name       : nmon
version    : 16f
release    : 1
source     :
    - http://heanet.dl.sourceforge.net/project/nmon/lmon16f.c : 280a371e17488f8a2c5e0c64273155789be6fa5b937ab5c465488e591bdc5cd9
license    : GPL-3.0
component  : system.utils
summary    : Linux performance monitoring on-screen or to CSV file
description: |
    Linux performance monitoring on-screen or to CSV file
extract    : no
build      : |
    ${CC} -o nmon ${sources}/lmon${version}.c ${CFLAGS} -D JFS -D GETUSER -D LARGEMEM -lncurses -lm
install    : |
    install -D -m 00755 nmon $installdir/usr/bin/nmon
